### ISSUE TITLE
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils (numpy==1.19.1)

### ISSUE THREAD

**Issue by lexycole** [fractalego/fact_checking#2]
Windows 10
Python: 3.11.2
python3: Python 3.10.10
Flask 2.2.3

Hi @fractalego and fact_checking team. So sorry to bug you here. but this error while installing fact_checking comes from numpy=1.19.1.
Project: Trying to build a url fake news app using flask 

```
error: subprocess-exited-with-error

No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils

**libraries mkl_rt not found** in ['C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib', 'C:\\', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\libs']
	NOT AVAILABLE

**libraries blis not found** in ['C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib', 'C:\\', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\libs']
        NOT AVAILABLE

**libraries openblas not found** in ['C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\lib', 'C:\\', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\\libs']

**libraries tatlas not found 
libraries satlas not found 
libraries ptf77blas,ptcblas,atlas not found
libraries f77blas,cblas,atlas not found 
 libraries blas not found 
libraries mkl_rt not found 
libraries openblas not found
libraries openblas,lapack not found 
libraries flame not found** 
```
![Screenshot (7399)](https://user-images.githubusercontent.com/40228505/227722230-47684789-f354-4ef9-a31e-4ceb2a8e41f1.png)
![Screenshot (7400)](https://user-images.githubusercontent.com/40228505/227722237-46a47572-3017-4621-8bce-799bd9e68d92.png)

**Comment by fractalego** [comment]
Hi lexycole, apologies for my late reply. I'm not sure what the issue is. Please let me try to replace it tomorrow

**Comment by fractalego** [comment]
Hi Lexycole, I cannot reproduce your error. However, searching online I found a potential fix: https://stackoverflow.com/questions/74359405/error-while-installing-pycaret-no-module-named-numpy-distutils-msvccompiler

It seems to be related to whether you have visual-cpp studio utils installed. Please try out that solution and let me know if it works.

**Comment by lexycole** [comment]
HI @fractalego, Thanks for the replies. I will be installing visual-cpp studio right now
