### ISSUE TITLE
Error "pip install fact_checking"

### ISSUE THREAD

**Issue by pndhuy150902** [fractalego/fact_checking#3]
Python version: 3.10.11
Cython version: 0.29.21

![image](https://github.com/fractalego/fact_checking/assets/84979154/9685a8ee-0a7b-4787-a4d0-6e2e767d31d0)
![image](https://github.com/fractalego/fact_checking/assets/84979154/0a768cba-9946-4aca-b788-7625f8ae401c)
![image](https://github.com/fractalego/fact_checking/assets/84979154/197ca3dd-5cd3-43ce-93be-ea31e73b5d02)

**Comment by fractalego** [comment]
Hello! Thank you for using this code. The issue at hand seems unrelated to the fact_checking module.

It seems that your system cannot install numpy. You could try to install it separately. Maybe this thread can help
https://github.com/numpy/numpy/issues/6917

Hope this helps!

**Comment by pndhuy150902** [comment]
Hi @fractalego, Thanks for the replies. Numpy 1.19.1 can not install in my system but when I install numpy in other version (1.23.5), my system can install it. And I clone source code from git and I use in my local system.

**Comment by fractalego** [comment]
Understood 😃 fact_checking should work well with later versions of numpy
